---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Cent0S"

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest  
    when: ansible_distribution == "Cent0S"
  
  - name: add php support for apache
    dnf:
       name: php
       state: latest
    when: ansible_distribution == "Cent0S"
